- name: "wait 600 seconds for target connection to become reachable/usable."
  ansible.builtin.wait_for_connection:
  timeout: 900
- name: Copy file with owner and permissions
  copy:
    src: ~//home/circleci/project/backend./dist
    dest: /var/www/html
    owner: udacity
    group: udacity
    mode: '0644'
