- name: "wait 600 seconds for target connection to become reachable/usable."
  ansible.builtin.wait_for_connection:
  timeout: 900
- name: Copy backend compressed file 
  become: true
  copy:
    src: /home/circleci/project/artifact.tar.gz
    dest: /home/ubuntu/backend/
- name: Extract backend files
  become: true
  shell: |
    cd /home/ubuntu/backend
    tar -vxf artifact.tar.gz
    rm artifact.tar.gz
- name : Compile and start app 
  become : true 
  shell : | 
    cd /home/ubuntu/backend
    npm install
    pm2 stop default
    pm2 start npm -- start

  environment:
    ENVIRONMENT: production
    NODE_ENV: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_MIGRATIONS_DIR: ~/src/migrations
    TYPEORM_MIGRATIONS: ~/src/migrations/*.ts
    TYPEORM_ENTITIES: ~/src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: databaseudacity.cufnzduvpdd9.us-east-1.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: yX7LvzRBf72pwZz
    TYPEORM_DATABASE: databaseudacity
