- name: "wait 600 seconds for target connection to become reachable/usable."
  ansible.builtin.wait_for_connection:
  timeout: 900
- name: Copy file with owner and permissions
  become: true

  copy:
    src: /home/circleci/project/backend/
    dest: /var/www/html
