version: 2.1

jobs:


    
  Build-Backend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]

      - run: |


          cd backend
          npm i
          npm run build

      - save_cache:
          paths: [backend/node_modules]
          key: backend-build



  Build-Frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]

      - run: |
          cd frontend
          npm install
          npm run start
          npm run build
          npm run prettier

      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

                  
  Test-Package:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run: |
          cd backend
          npm run test

workflows:
  Default:
    jobs:
      - Build-Frontend
      - Build-Backend

