version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  Install-Dependencies:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run : |
            cd backend/
            npm i
            cd ..
            cd frontend/
            npm i
      - persist_to_workspace:
          root: ~/project
          paths: .

    
  Build-Backend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run: |
          cd backend
          npm install
          npm run start
  Test-Package:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run: |
          cd backend
          npm run test

workflows:
  Default:
    jobs:
      - Install-Dependencies

