version: 2.1


jobs:
  Build-Backend:
    docker:
      - image: cimg/node:15.0.1
    steps:
      - checkout
      - run: |
          cd backend
          npm install  

workflows:
  Default:
    jobs:
      - Build-Backend
