version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:


    
  Build-Backend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run: |


          cd backend
          npm install
          npm run start
  Test-Package:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run: |
          cd backend
          npm run test

workflows:
  Default:
    jobs:
      - Build-Backend

