version: 2.1
orbs:
  slack: circleci/slack@4.9.3


jobs:
       
  Build-Backend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout

      - run: |
          cd backend
          npm i
          npm run build
      
      - save_cache:
          paths: 
            - backend/node_modules
            - backend/dist            
          key: backend-build -{{ checksum "package-lock.json" }}
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1


  Build-Frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout

      - run: |
          cd frontend
          npm i
          npm run build

      - save_cache:
          paths: 
            - frontend/node_modules
            - frontend/dist
          key: frontend-build -{{ checksum "package-lock.json" }}
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

  Test-Frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          key: frontend-build -{{ checksum "package-lock.json" }}
      - run: |
          cd frontend
          npm test
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
  Test-Backend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          key: backend-build -{{ checksum "package-lock.json" }}
      - run: |
          cd backend
          npm test
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1



  Scan-Frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          key : frontend-build -{{ checksum "package-lock.json" }}
      - run : 
          name: Fix Audit problems Frontend

          command : |
            cd frontend
            npm install
            npm audit fix --audit-level=critical --force
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
  Scan-Backend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          key : backend-build -{{ checksum "package-lock.json" }}
      - run : 
          name: Fix Audit problems Backend
          command : |
            cd backend
            npm audit fix --audit-level=critical --force
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
workflows:
  Default:
    jobs:
      - Build-Frontend : 
          context: slacknotifications

      - Build-Backend : 
          context: slacknotifications

      - Test-Frontend :
          requires : 
            - Build-Frontend
          context: slacknotifications

      - Test-Backend: 
          requires : 
            - Build-Backend
          context: slacknotifications

      - Scan-Frontend : 
          requires:
            - Test-Frontend
          context: slacknotifications
      - Scan-Backend: 
          requires:
            - Test-Backend
          context: slacknotifications


     
